#Setup/install tasks
- include_tasks: setup_grafana-alloy_debian.yaml
  when: ansible_facts.os_family == 'Debian'

- include_tasks: setup_grafana-alloy_arch.yaml
  when: ansible_facts.os_family == 'Archlinux'
